### ISSUE TITLE
nengo_dl.Simulator Crashes in the Example Code in the repository readme!

### ISSUE THREAD

**Issue by MarinaHesham** [nengo/nengo-dl#135]
Hi, 

I was getting started with nengo-dl, I started with the Example Code in the repository readme, but the code crashes at nengo_dl.Simulator.

I tried other examples code provided but I get the same error, I also tried to run on google colab and a virtual environment in case there is a conflict with the versions on my machine but I still got the same error.

Is it expecting specific versions of python or tensorflow, I am using python 3.7 and tensorflow 2.1.

This is the error I got!

Traceback (most recent call last):
  File "nengodl_digit_class.py", line 11, in <module>
    with nengo_dl.Simulator(net, seed=0,minibatch_size=200, progress_bar=True) as sim: # this is the only line that changes
  File "/Users/marinaneseem/Documents/Research/SNNs/src/nengo-dl/nengo_dl/simulator.py", line 516, in __init__
    seed,
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/training/tracking/base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/Users/marinaneseem/Documents/Research/SNNs/src/nengo-dl/nengo_dl/tensor_graph.py", line 124, in __init__
    old_operators = operators
  File "/usr/local/lib/python3.7/site-packages/progressbar/bar.py", line 548, in __exit__
    self.finish(dirty=bool(exc_type))
TypeError: finish() got an unexpected keyword argument 'dirty'

Thanks.

**Comment by tbekolay** [comment]
Hi @MarinaHesham, thanks for the bug report! As it turns out, the progress bar library that we use released a new version two days ago and introduced the bug. I've made a fix for it (#136) which we'll release as soon as possible.

**Comment by MarinaHesham** [comment]
Hi @tbekolay, Thanks for your quick response.
