### ISSUE TITLE
ImportError: cannot import name 'network' from 'tensorflow.python.keras.engine' with TensorFlow 2.3.0

### ISSUE THREAD

**Issue by Tioz90** [nengo/nengo-dl#167]
I just compiled TensorFlow 2.3.0 from source but I'm getting the following error when trying to run my code:

`Traceback (most recent call last):
  File "/Users/thomastiotto/opt/anaconda3/envs/nengodl_opt/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-8961a12e9037>", line 1, in <module>
    runfile('/Users/thomastiotto/PycharmProjects/Memristor_Learning/experiments/test_builder_mPES.py', wdir='/Users/thomastiotto/PycharmProjects/Memristor_Learning/tests')
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/thomastiotto/PycharmProjects/Memristor_Learning/experiments/test_builder_mPES.py", line 2, in <module>
    import nengo_dl
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/thomastiotto/opt/anaconda3/envs/nengodl_opt/lib/python3.7/site-packages/nengo_dl/__init__.py", line 58, in <module>
    from nengo_dl import callbacks, compat, converter, dists, losses
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/thomastiotto/opt/anaconda3/envs/nengodl_opt/lib/python3.7/site-packages/nengo_dl/callbacks.py", line 20, in <module>
    from nengo_dl import compat, utils
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/thomastiotto/opt/anaconda3/envs/nengodl_opt/lib/python3.7/site-packages/nengo_dl/compat.py", line 14, in <module>
    from tensorflow.python.keras.engine import network
ImportError: cannot import name 'network' from 'tensorflow.python.keras.engine' (/Users/thomastiotto/opt/anaconda3/envs/nengodl_opt/lib/python3.7/site-packages/tensorflow/python/keras/engine/__init__.py)
`

Everything was fine in TensorFlow 2.1.0 so it seems as if something changed internally in either v2.2.0 or 2.3.0 .

**Comment by drasmuss** [comment]
What does your `tf.__version__` display? I suspect you're using a source version in between the 2.2.0 and 2.3.0 releases.  `tensorflow.python.keras.engine.network` was removed in that window, so NengoDL sees that you have a version < 2.3.0 (when that change was made official), and assumes you're using the 2.2.0 API. If you upgrade to the latest TensorFlow development version (2.4.0) then everything should be fine. Alternatively, you could take your current TensorFlow branch and change the version to something like 2.3.1 (in this file https://github.com/tensorflow/tensorflow/blob/c7fa71b32a3635eb25596ae80d007b41007769c4/tensorflow/core/public/version.h#L23), so that NengoDL will know to treat it as >= 2.3.0.

**Comment by drasmuss** [comment]
NengoDL 3.3.0 has now been released, so this should be resolved!

**Comment by Tioz90** [comment]
Great, but the breaking changes introduced to the build process could have been documented and pointed out :)

**Comment by drasmuss** [comment]
There is this section in the [release notes](https://github.com/nengo/nengo-dl/releases/tag/v3.3.0):

> Internal NengoDL OpBuilder classes now separate the "pre build" stage from `OpBuilder.__init__` (so that the same OpBuilder class can be re-used across multiple calls, rather than instantiating a new OpBuilder each time). Note that this has no impact on front-end users, this is only relevant to anyone that has implemented a custom build class. The logic that would previously have gone in `OpBuilder.__init__` should now go in `OpBuilder.build_pre`. In addition, the ops argument has been removed from `OpBuilder.build_pre`; that will be passed to `OpBuilder.__init__` ( and will be available in `build_pre` as `self.ops`). Similarly, the ops and config argument have been removed from `build_post`, and can instead be accessed through `self.ops/config`. 

Or is it a different change you are referring to?

**Comment by Tioz90** [comment]
Yes, that exactly.  I read through the notes but missed that one, sorry!
