### ISSUE TITLE
RuntimeError: threads can only be started once

### ISSUE THREAD

**Issue by Edward-CNRG-NTU** [nengo/nengo-dl#38]
https://github.com/nengo/nengo-dl/blob/b9e7ae57906feb56d8d7d37a90b8d46a55fc2ea3/nengo_dl/utils.py#L353

********
Building network
Build finished in 0:00:01 
|#                                    Optimizing graph                                      | 0:00:00Traceback (most recent call last):
  File "MSO_model.py", line 158, in <module>
    run_MSO_model()
  File "MSO_model.py", line 128, in run_MSO_model
    sim = build_model()
  File "MSO_model.py", line 119, in build_model
    sim = nengo_dl.Simulator(model, dt=dt, unroll_simulation=1)
  File "/home/cnrg-ntu/nengo-dl/nengo_dl/simulator.py", line 138, in __init__
    max_value=None) as progress:
  File "/home/cnrg-ntu/nengo-dl/nengo_dl/utils.py", line 353, in __enter__
    return self.start()
  File "/home/cnrg-ntu/nengo-dl/nengo_dl/utils.py", line 294, in start
    self.thread.start()
  File "/usr/lib/python2.7/threading.py", line 730, in start
    raise RuntimeError("threads can only be started once")
RuntimeError: threads can only be started once
|      #                              Optimizing graph                                      | 0:00:00

********
just change to:
```
return self
```
seems to fix it.

**Comment by drasmuss** [comment]
I think you may have an older version of the `progressbar2` package, if you do `pip install progressbar2 --upgrade` that should fix it.

**Comment by drasmuss** [comment]
The latest release updates the minimum `progressbar` version to 3.37.1, which should resolve this.  Let me know if that isn't the case, and I'll reopen the issue!
